### ISSUE TITLE
Local Fullscreen Not Sizing Correctly

### ISSUE THREAD

**Issue by dtt788** [FredTungsten/ScriptPlayer#214]
![image](https://user-images.githubusercontent.com/97572724/149052659-74725d85-eeaa-433c-8d09-8492ecabf6ea.png)
When I use the local video player and fullscreen the video gets pushed too far to the right and as a result gets cut off. (full screen cap  above)

Also, noticed the playback bar at the bottom is pushed too far off the edge of the screen and the bar at the top doesn't go away. I'm guessing its just pinned and that the pin button is getting pushed off the edge as well.

![image](https://user-images.githubusercontent.com/97572724/149053200-1277d7d1-d948-427f-a7a6-9f46a0c401dd.png)
This is when I try to fullscreen on my second monitor, the problem worsens by the window not correctly filling up

I'm on Windows 10 Pro, using latest Scriptplayer version 1.1.1.371 from the beta builds. 

Resolution on my main monitor is 2560 x 1440 and my second monitor is 1600 x 900

**Comment by FredTungsten** [comment]
Hey, sorry for the delayed response.
Unfortunately I haven't been able to reproduce this issue - I've tried every conceivable combination of monitor arrangement, resolution and even display scaling, but it always fills the screen correctly.

**Comment by dtt788** [comment]
Hey no problem, I appreciate you trying. I switched to using MPC as my video player so it didn't get into the way that much. Next time I'll try reinstalling everything and seeing if that fixes it.

**Comment by EleumR** [comment]
Same issue, I'll try reinstalling and see if that changes anything. Running on 1440p with the local video player, if you need any more information please let me know.

**Comment by SomeoneFarAway** [comment]
This only happens on a multimonitor setup, where the displays have different resolutions (in my experience)

Try disabling one monitor and look if it works correctly.

Also in the latest build (from source) this issue is already fixed

**Comment by EleumR** [comment]
Second monitor has indeed a different resolution (1080p) but switching it off does nothing, video is still clipping out of frame. Running on 1.1.1.392, tested both the release and debug versions, even after full reinstall the problem persists.

**Comment by SomeoneFarAway** [comment]
@EleumR did you "just" turn off the second monitor or did you disable it in the windows display settings?

just turning it off will not work in most cases (it works if it is connected via displayport), since your PC still thinks something is connected.

you have to explicitly set it to `Only use Display 1` (phrasing may vary, since english is not my native language)
