### ISSUE TITLE
Specify launch monitor

### ISSUE THREAD

**Issue by mument** [FredTungsten/ScriptPlayer#84]
Just a bit of a minor annoyance, but for some reason ScriptPlayer always opens up on my secondary monitor regardless of where it was placed on closing or whether my secondary monitor is set as my 'main display' (if that makes sense). Do you know a way to force it to open on one monitor every time? It's not a priority issue, but I thought I'd ask! :-)

**Comment by FredTungsten** [comment]
Shouldn't be too hard. I'll notify you when I got something.

**Comment by mument** [comment]
Cheers mate, you're a star!I just wanted to pass on that it's a really great bit of software and it's great to have a developer who is so keen to keep improving,

    On Thursday, February 28, 2019, 5:04:59 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
Shouldn't be too hard. I'll notify you when I got something.

**Comment by FredTungsten** [comment]
I just pushed a new feature that's now available in the latest beta-build (https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds).

In the settings window in the tab "Remember", activate "Window Position".
When you close ScriptPlayer it should remember the position and state it was last in.
(Not 100% sure if it will work with multiple monitors, but it should)

**Comment by mument** [comment]
Thanks for adding this, but it doesn't seem to work on my setup. I just don't understand why it insists on opening up on the secondary monitor, when nothing else does, unless it is set to do so. Weird.     On Saturday, March 2, 2019, 11:53:51 AM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
I just pushed a new feature that's now available in the latest beta-build (https://github.com/FredTungsten/ScriptPlayer/wiki/Downloading-Beta-Builds).

In the settings window in the tab "Remember", activate "Window Position".
When you close ScriptPlayer it should remember the position and state it was last in.
(Not 100% sure if it will work with multiple monitors, but it should)

**Comment by FredTungsten** [comment]
Just to be sure: Remember Window Position is enabled in the settings?

**Comment by FredTungsten** [comment]
I just changed a small detail that might fix it (latest beta build).
Still don't know why it didn't but maybe it does now.

If it doesn't, please check the following things:
- Does it remember the correct position on the "wrong" monitor or does it not remember it at all?
- It should save the position of the window, if it's maximized and if it's in fullscreen mode. Does ANY of that work for you?
- Can you post your `%AppData%\ScriptPlayer\PlayerState.xml`?

**Comment by mument** [comment]
Okay, this is a bit weird. It sort of works. If I move the window to the correct monitor and keep it in a window when I close it (i.e. not maximised) it reopens on the correct monitor (not maximised) - it actually starts on the other monitor and then zips across when it's fully loaded up. If I close it on the correct monitor when it is full-screen (maximised) it reopens maximised on the wrong monitor, but if I then restore the size to a window (using the top-right window button) it then zips across to the correct monitor. 
One thing I notice is that it still spawns the playlist window on the wrong monitor whatever I do.
    On Wednesday, March 6, 2019, 4:02:48 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
I just changed a small detail that might fix it (latest beta build).
Still don't know why it didn't but maybe it does now.

If it doesn't, please check the following things:
   
   - Does it remember the correct position on the "wrong" monitor or does it not remember it at all?
   - It should save the position of the window, if it's maximized and if it's in fullscreen mode. Does ANY of that work for you?
   - Can you post your %AppData%\ScriptPlayer\PlayerState.xml?

**Comment by FredTungsten** [comment]
Still doesn't sound good enough, but at least it's a step in the right direction.
(The playlist-window isn't being tracked at all yet btw.)
I don't when I'll have time to tinker with this again so it will _might_ stay like this for a while.

**Comment by mument** [comment]
No problem. Any progress is always appreciated and we're all busy people! Thanks again.
    On Thursday, March 7, 2019, 6:30:38 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
Still doesn't sound good enough, but at least it's a step in the right direction.
(The playlist-window isn't being tracked at all yet btw.)
I don't when I'll have time to tinker with this again so it will might stay like this for a while.

**Comment by FredTungsten** [comment]
Well, the _"it actually starts on the other monitor and then zips across when it's fully loaded up"_  just gave me an idea what the problem might be. I pushed another version - I wouldn't get my hopes up though, I'm pretty much stabbing in the dark here.

**Comment by mument** [comment]
Okay, it's definitely had an effect . I'll try and work out exactly what is happening. When I first loaded up, it loaded up maximised on the primary monitor (the one I want) and the playlist did too. When I close it from maximised, it loads up next time on the secondary monitor in a maximised window. If I 'restore' the window, it zips across to the primary monitor where it can be maximised manually. If I close the window in a non-maximised state on the primary monitor, it loads up next time as maximised on the primary monitor. The playlist always loads up on the secondary monitor, except for the very first time loading after installing the beta - when both the main player and the playlist opened on the primary monitor. I hope that makes sense!
Thanks for your help.    On Thursday, March 7, 2019, 7:31:37 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
Well, the "it actually starts on the other monitor and then zips across when it's fully loaded up" just gave me an idea what the problem might be. I pushed another version - I wouldn't get my hopes up though, I'm pretty much stabbing in the dark here.

**Comment by FredTungsten** [comment]
Ahw man, I really thought I finally fixed it 😞 
Instead of having you test 100 different versions I'll hook up another display when I find the time.
I'll @ you when I have a version that works.

**Comment by mument** [comment]
Cheers. It must be a pain having to try and hypothetically fix these problems. Sounds like a plan. 
    On Friday, March 15, 2019, 12:06:17 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 
Ahw man, I really thought I finally fixed it 😞
Instead of having you test 100 different versions I'll hook up another display when I find the time.
I'll @ you when I have a version that works.
